### ISSUE TITLE
Does the help-surarez code support multiple nodes, cores, or GPU usage?

### ISSUE THREAD

**Issue by teopb** [CliMA/ClimaHeldSuarez.jl#2]
Sorry for the general nature of the question. It is not really clear to me from this documentation or that in ClimaCore.jl how to actually go about running the code. I'd like to run some pretty simple Held-Suarez setups but am not sure what kind of computational environment is supported. Can I run across multiple nodes on a cluster? Will the Clima code detect available cores and GPUS automatically? Thanks for any help!

**Comment by glwagner** [comment]
@teopb that's a fair question! This repo isn't very useful (we were planning to do more work with it, but it was superceded by higher priority tasks). Still, you could try running this script:

https://github.com/CliMA/ClimaHeldSuarez.jl/blob/main/reference/run_held_suarez_experiment.jl

That should make a plot of the zonal velocity at the end, eg

https://github.com/CliMA/ClimaHeldSuarez.jl/blob/d501ad8981167c65bbd9cc8e95b2c7f64f28b5ed/reference/run_held_suarez_experiment.jl#L167-L176

It's not my purview, but I suspect that to run some simple Held-Suarez setups you want to look to ClimaAtmos:

https://github.com/CliMA/ClimaAtmos.jl

I definitely suggest getting in touch there via issues or discussions.

**Comment by teopb** [comment]
@glwagner Thanks so much for pointing me in the right direction!
